# Cloudflare Pages 配置文件
name = "tutoring-center-react-app"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "frontend"
publish = "frontend/dist"

[build.environment_variables]
NODE_VERSION = "18"